namespace AivoraPOS.Core.Constants;

public static class ProductInfo
{
    public const string AppName = "AivoraPOS";
    public const string CompanyName = "Aivora Technologies";
    public const string Tagline = "Your Vision, Our Technology";
    public const string SupportEmail = "[YOUR EMAIL HERE]";
    public const string Publisher = CompanyName;
    public const string UpdateFeedUrl = "https://updates.mycompany.com/aivorapos/version.json";
    public const string CrashReportUrl = "https://updates.mycompany.com/aivorapos/crashes";

    public static string Copyright => $"© {DateTime.Now.Year} {CompanyName}. All rights reserved.";

    public static string CopyrightShort => $"© {DateTime.Now.Year} {CompanyName}";

    public static string WindowTitle => $"{AppName} — {CompanyName}";

    public static string TrayTooltip => $"{AppName} — {CompanyName}";

    public static string ReceiptAttribution => $"Software by {CompanyName}";

    public static string PdfGeneratedBy => $"Generated by {AppName}";

    public static string PdfFooterRight(int? year = null) =>
        $"{AppName} {CopyrightShort}";

    public static string PoweredBy => $"Powered by {CompanyName}";
}
